// creating states for the game. the value of these don't actually matter all that much so i just used rrandom phrases that came to mind
const COUNTDOWN = 'ITS THE FINAL COUNTDOWN!!!!';
const PLAYING = 'DONT HATE THE PLAYER HATE THE GAME'; // find a musical reference for this state
const PAUSED = 'STOP! COLLABORATE AND LISTEN';
const ENDGAME = "WE'RE IN THE END GAME NOW"; // find a musical reference for this state
const NO_MIDI_SUPPORT = "Y U NO USE CHROME"; // find a musical reference for this state
const NO_MIDI = "PLUG IT IN";
const MAIN_MENU = 1;
const FINGER_TECHNIQUE = 2;
const CHORDS = 3;
const PLAY_SONG = 4;
const HIT_THREASHOLD = 10;
const FALLING = "I'M FREEEEEE, FREE FALLING!!!";
const OUT_OF_BOUNDS = "OUT OF HERE"; // find a musical reference for this state
const MISSED = "MOANING";
const HIT = "HIT ME BABY ONE MORE TIME";
const NOT_YET_HIT = 'NOT YET HIT';
const LEFT_HAND = 'LEFT';
const RIGHT_HAND = 'RIGHT';
const FINGER1_NAME = 'thumb';
const FINGER2_NAME = 'index';
const FINGER3_NAME = 'middle';
const FINGER4_NAME = 'ring';
const FINGER5_NAME = 'pinky';
const LEFT_FINGER1_CODE = 'L1';
const LEFT_FINGER2_CODE = 'L2';
const LEFT_FINGER3_CODE = 'L3';
const LEFT_FINGER4_CODE = 'L4';
const LEFT_FINGER5_CODE = 'L5';
const RIGHT_FINGER1_CODE = 'R1';
const RIGHT_FINGER2_CODE = 'R2';
const RIGHT_FINGER3_CODE = 'R3';
const RIGHT_FINGER4_CODE = 'R4';
const RIGHT_FINGER5_CODE = 'R5';
const N_BLACK = 25;
const N_WHITE = 36;
const STARTING_KEY_NUMBER = 36;
const black = "#262A2A";// #262A2A {r:0,g:0,b:0};
const white = "#F9F9EF";// #F9F9EF {r:0,g:0,b:0};
const red = "#EF131A";// #EF131A {r:0,g:0,b:0};
const blue = "#54A9E5";// #54A9E5 {r:0,g:0,b:0};
const orange = "#FD9025";// #FD9025 {r:0,g:0,b:0};
const green = "#D2DE47"; // #D2DE47 {r:0,g:0,b:0};
const grey = "#444748"; // #444748 